import type { Metadata } from 'next';
import './globals.css';
import { BaseLayout } from '@/shared/components/layouts';
import { QueryProvider, UserProvider } from '@/shared/components/providers';
import { Noto_Serif_KR } from 'next/font/google';

const notoserif = Noto_Serif_KR({ weight: ['200'] });

export const metadata: Metadata = {
  title: 'next-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={notoserif.className}>
        <UserProvider>
          <QueryProvider>
            <BaseLayout>{children}</BaseLayout>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
