import type { Metadata } from 'next';
import './globals.css';
import { BaseLayout } from '@/shared/components/layouts';
import { QueryProvider } from '@/shared/components/providers';

export const metadata: Metadata = {
  title: 'next-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='kor'>
      <body>
        <QueryProvider>
          <BaseLayout>{children}</BaseLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
